# Generated by Django 2.1.5 on 2020-03-26 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.IntegerField(default=0)),
                ('spent_date', models.DateTimeField()),
                ('hunter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lend_or_borrow_date', models.DateField()),
                ('deadline', models.DateField()),
                ('no_days', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('amount', models.IntegerField(default=0)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('type_of_record', models.CharField(blank=True, max_length=100)),
                ('hunter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
