# Generated by Django 2.1.5 on 2020-03-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20200327_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='record',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='record',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
